FROM golang:1.18-alpine as builder

ARG PKG_NAME=github.com/JayJamieson/DAT
ARG ENV="production"

# installs certs require
RUN apk update && apk add --no-cache git ca-certificates && update-ca-certificates

COPY . /go/src/${PKG_NAME}

RUN cd /go/src/${PKG_BASE}/${PKG_NAME} && \
    CGO_ENABLED=0 GOOS=linux go build -ldflags="-X 'main.environment=$ENV'" -a -installsuffix cgo -o /main

FROM scratch

COPY --from=builder /main .


ENTRYPOINT [ "./main" ]
